### ISSUE TITLE
Introduce gosec

### ISSUE THREAD

**Issue by nao1215** [go-spectest/spectest#11]
Introduce gosec. For example;

```yml
name: Gosec
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
```
